# Workflow de Integração Contínua responsável por executar os testes unitários.
# Estrutura preparada para futuras expansões, mantendo um único job dedicado aos testes.

name: Continuous Integration

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '24'
  VERCEL_TOKEN: ${{ SECRETS.VERCEL_TOKENS }}
  VERCEL_PROJECT_ID: ${{ SECRETS.VERCEL_PROJ_ID}}
  VERCEL_ORG_ID: ${{ SECERETS.VERCEL_ORG_ID }}
  VERCEL_SCOPE: ${{ SCRETS.VERCEL_SCOPE }}

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      # Obtém o código-fonte do repositório.
      - name: Checkout repository
        uses: actions/checkout@v7.0.0

      # Configura a versão do Node.js utilizada pelo projeto.
      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Habilita o Corepack para gerenciamento do Yarn.
      - name: Enable Corepack
        run: corepack enable

      # Instala as dependências do projeto.
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Executa os testes unitários.
      - name: Run unit tests
        run: yarn test
  build-and-deploy:
    name: build & deploy vercel Preview
    needs: [unit-tests]
    runs-on: ubuntu-latest

    steps:
      # Obtém o código-fonte do repositório.
      - name: Checkout repository
        uses: actions/checkout@v7.0.0

      # Configura a versão do Node.js utilizada pelo projeto.
      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Habilita o Corepack para gerenciamento do Yarn.
      - name: Enable Corepack
        run: corepack enable

      # Instala as dependências do projeto.
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      # Build Vercel
      - name: Build Vercel
        run: yarn vercel build --token=$VERCEL_TOKEN

      # Deploy Preview no Vercel
      - name: Vercel Deploy Preview
        run: yarn vercel deploy --prebuilt --target=preview --token=$VERCEL_TOKEN --scope=$VERCEL_SCOPE